######################################################################
# Automatically generated by qmake (3.0) Mon Oct 27 00:15:51 2014
######################################################################

TEMPLATE = app
TARGET = Tic-Tac-Toe
INCLUDEPATH += .

# Input
HEADERS += dialog.h mainwindow.h tictactoe.h
FORMS += dialog.ui mainwindow.ui
SOURCES += dialog.cpp main.cpp mainwindow.cpp tictactoe.cpp
